package MainPage;

import javax.swing.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Akshay
 */

public class LoginForm extends javax.swing.JFrame {
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("E:\\Java Project\\untitled\\src\\Images\\icon.png");
        setIconImage(icon);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginSection = new javax.swing.JPanel();
        UsernameTitle = new javax.swing.JLabel();
        LoginTitle = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        PasswordTitle = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        LoginBt = new javax.swing.JButton();
        SignBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TitlePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SymbiLife - ( LOGIN / SIGNUP )");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginSection.setBackground(new java.awt.Color(255, 153, 153));
        LoginSection.setForeground(new java.awt.Color(102, 102, 255));
        LoginSection.setOpaque(false);

        UsernameTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UsernameTitle.setText("Username / Email");

        LoginTitle.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        LoginTitle.setText("Login Page");

        Username.setBackground(new java.awt.Color(232, 243, 255));
        Username.setToolTipText("Username or Email");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        PasswordTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordTitle.setText("Password");

        Password.setBackground(new java.awt.Color(232, 242, 255));
        Password.setText("jPasswordField1");

        LoginBt.setBackground(new java.awt.Color(0, 204, 204));
        LoginBt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        LoginBt.setForeground(new java.awt.Color(255, 255, 255));
        LoginBt.setText("Login");
        LoginBt.setPreferredSize(new java.awt.Dimension(75, 22));
        LoginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Database db = new Database();
                ResultSet rs = db.searchStudent(Username.getText());

                try {
                    if (rs.next())
                    {
                        String password = rs.getString("password");
                        String enteredPassword = String.valueOf(Password.getPassword());
                        if (password != null && password.equals(enteredPassword)) {
                            HomePage homePage = new HomePage();
                            homePage.setVisible(true);
                            dispose();
                        }
                    }
                    else
                    {
                        String message="Please enter correct password";
                        JOptionPane.showMessageDialog(null, message);
                    }
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        SignBt.setBackground(new java.awt.Color(0, 204, 204));
        SignBt.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        SignBt.setForeground(new java.awt.Color(255, 255, 255));
        SignBt.setText("Sign-up");
        SignBt.setMargin(new java.awt.Insets(6, 14, 3, 14));
        SignBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginSectionLayout = new javax.swing.GroupLayout(LoginSection);
        LoginSection.setLayout(LoginSectionLayout);
        LoginSectionLayout.setHorizontalGroup(
                LoginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginSectionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                        .addGroup(LoginSectionLayout.createSequentialGroup()
                                .addGroup(LoginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(LoginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(LoginSectionLayout.createSequentialGroup()
                                                        .addGap(28, 28, 28)
                                                        .addGroup(LoginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(PasswordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                                                .addComponent(UsernameTitle)
                                                                .addComponent(Password)))
                                                .addComponent(SignBt, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                                        .addComponent(LoginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        LoginSectionLayout.setVerticalGroup(
                LoginSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginSectionLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(LoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UsernameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(PasswordTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LoginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SignBt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(LoginSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 320, 430));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setForeground(new java.awt.Color(122, 188, 255));
        jLabel1.setText("www.sitpune.edu.in");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 290, -1));

        TitlePanel.setBackground(new java.awt.Color(204, 255, 255));
        TitlePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon icon1 = new ImageIcon("E:\\Java Project\\untitled\\src\\Images\\background.jpg");
        TitlePanel.setIcon(icon1); // NOI18N
        TitlePanel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TitlePanel.setAlignmentY(0.0F);
        TitlePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TitlePanel.setInheritsPopupMenu(false);
        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtActionPerformed
        // TODO add your handling code here:
        new HomePage().setVisible(true); // Main Form to show after the Login Form..
        this.dispose();
    }//GEN-LAST:event_LoginBtActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void SignBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignBtActionPerformed
        // TODO add your handling code here:
        new StudentManagementSys().setVisible(true); // Main Form to show after the Login Form..
        this.dispose();
    }//GEN-LAST:event_SignBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBt;
    private javax.swing.JPanel LoginSection;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordTitle;
    private javax.swing.JButton SignBt;
    private javax.swing.JLabel TitlePanel;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
